trigger:
  branches:
    include:
      - staging
      - qa
      - prod

pr:
  branches:
    include:
      - qa
      - prod

pool:
  name: azureagent

steps:
  - task: Bash@3
    displayName: Deploy to VM on correct port
    inputs:
      targetType: 'inline'
      script: |
        echo "== Detecting branch =="
        RAW_BRANCH="${BUILD_SOURCEBRANCH#refs/heads/}"
        echo "Branch is: $RAW_BRANCH"

        if [ "$RAW_BRANCH" = "staging" ]; then
          PORT=3001
          PM2_NAME="appnode-staging"
        elif [ "$RAW_BRANCH" = "qa" ]; then
          PORT=3002
          PM2_NAME="appnode-qa"
        elif [ "$RAW_BRANCH" = "prod" ]; then
          PORT=3003
          PM2_NAME="appnode-prod"
        else
          echo "❌ Unknown branch: $RAW_BRANCH"
          exit 1
        fi

        echo "== Using PORT: $PORT and PM2 process name: $PM2_NAME =="
        
        APP_DIR="/home/azureuser/${RAW_BRANCH}-app"
        echo "== Cloning $RAW_BRANCH into $APP_DIR =="
        rm -rf $APP_DIR
        git clone -b $RAW_BRANCH https://github.com/raool1/appnode $APP_DIR
        cd $APP_DIR

        echo "== Installing dependencies =="
        npm install

        echo "== Building the app =="
        npm run build

        echo "== Starting app with PM2 =="
        pm2 delete "$PM2_NAME" || true
        PORT=$PORT pm2 start server.js --name "$PM2_NAME"

        echo "✅ Deployment finished for $RAW_BRANCH on port $PORT"

