trigger:
  branches:
    include:
      - prod
      - qa
      - staging

pool:
  name: azureagent

jobs:
- job: DeployToVM
  displayName: "Deploy based on branch"
  steps:
    - checkout: self

    - task: Bash@3
      displayName: "Deploy to VM on correct port"
      inputs:
        targetType: 'inline'
        script: |
          echo "== Detecting branch =="
          BRANCH="$(Build.SourceBranchName)"
          echo "Branch is: $BRANCH"

          if [[ "$BRANCH" == "refs/heads/staging" ]]; then
            PORT=3001
            APPNAME="appnode-staging"
          elif [[ "$BRANCH" == "refs/heads/qa" ]]; then
            PORT=3002
            APPNAME="appnode-qa"
          elif [[ "$BRANCH" == "refs/heads/prod" ]]; then
            PORT=3003
            APPNAME="appnode-prod"
          else
            echo "❌ Unknown branch: $BRANCH"
            exit 1
          fi

          echo "== Using port: $PORT and app name: $APPNAME =="

          cd /home/azureuser/appnode

          echo "== Pulling latest code =="
          git fetch origin
          git reset --hard
          git checkout ${BRANCH#refs/heads/}
          git pull origin ${BRANCH#refs/heads/}

          echo "== Installing dependencies =="
          npm install

          echo "== Building app =="
          npm run build || echo "⚠️ Skipping build (if not needed)"

          echo "== Restarting app with PM2 =="
          pm2 delete $APPNAME || true
          PORT=$PORT pm2 start server.js --name "$APPNAME"

          echo "✅ Deployment complete: $APPNAME running on port $PORT"
