trigger:
  branches:
    include:
      - staging
      - qa
      - prod

pool:
  vmImage: ubuntu-latest

steps:
  - task: Bash@3
    displayName: Deploy to VM on correct port
    inputs:
      targetType: 'inline'
      script: |
        echo "== Detecting branch =="
        RAW_BRANCH="${BUILD_SOURCEBRANCH#refs/heads/}"
        echo "Branch is: $RAW_BRANCH"

        if [ "$RAW_BRANCH" = "staging" ]; then
          PORT=3001
        elif [ "$RAW_BRANCH" = "qa" ]; then
          PORT=3002
        elif [ "$RAW_BRANCH" = "prod" ]; then
          PORT=3003
        else
          echo "❌ Unknown branch: $RAW_BRANCH"
          exit 1
        fi

        echo "== Using port: $PORT =="
        echo "== Cloning latest code =="

        git pull origin $RAW_BRANCH

        echo "== Installing dependencies =="
        npm install

        echo "== (Optional) Building the app =="
        npm run build

        echo "== Starting app with PM2 =="
        pm2 delete all || true
        pm2 start index.js --name "appnode" -- -p $PORT
